		-- 1.Database Exploration

-- Explore all objects in the database

SELECT * FROM INFORMATION_SCHEMA.TABLES; 

-- Explore all columns in the database

SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'customers';


		-- 2.Dimensions Exploration

-- Explore all countries our customers come form

SELECT DISTINCT country FROM customers;

-- Explore the categories/ divisions of products

SELECT DISTINCT 
category, subcategory, product_name
FROM products;


		-- 3.Dates Exploration
            
-- Find the first and last order date
-- How many years of sales data is available

SELECT
MIN(order_date) as first_order_date,
MAX(order_date) as last_order_date,
TIMESTAMPDIFF(MONTH, MIN(order_date), MAX(order_date)) as order_range_months
FROM sales;

-- Find the youngest and the oldest customer

SELECT
MAX(birthdate) AS youngest_customer_bd,
TIMESTAMPDIFF(YEAR, MAX(birthdate), CURDATE()) AS youngest_customer_age,
MIN(birthdate) AS oldest_customer_bd,
TIMESTAMPDIFF(YEAR, MIN(birthdate), CURDATE()) AS oldest_customer_age
FROM customers;


		-- 4.Measures Exploration
        
-- Find the total revenue

Select 
SUM(sales_amount) as total_revenue
FROM sales;

-- Find total quantity of products sold

SELECT
SUM(quantity) as quantity_sold
FROM sales;

-- Find the average selling price

SELECT 
ROUND(AVG(price),2) as avg_selling_price
FROM sales;

-- Find the total no. of orders

SELECT
COUNT(DISTINCT order_number) as total_orders
FROM sales;

-- Find the total no. of products

SELECT
COUNT(DISTINCT product_name) AS total_products
FROM products;

-- Find the total number of customers

SELECT
COUNT(DISTINCT customer_key) as total_customers
FROM customers;

-- Find the total number of customers that has placed an order

SELECT
COUNT(DISTINCT customer_key) AS active_customers
FROM sales;

-- Generate a report that shows all key metrics of the business

SELECT 
    'Total Revenue' AS measure_name,
    SUM(sales_amount) AS measure_value
FROM
    sales 
UNION ALL SELECT 
    'Quantity Sold', SUM(quantity)
FROM
    sales 
UNION ALL SELECT 
    'Avg. Selling Price', ROUND(AVG(price), 2)
FROM
    sales 
UNION ALL SELECT 
    'Total Orders', COUNT(DISTINCT order_number)
FROM
    sales 
UNION ALL SELECT 
    'Total Products', COUNT(DISTINCT product_name)
FROM
    products 
UNION ALL SELECT 
    'Total Customers', COUNT(DISTINCT customer_key)
FROM
    customers 
UNION ALL SELECT 
    'Active Customers', COUNT(DISTINCT customer_key)
FROM
    sales;
    
    
    
		-- 5.Magnitude Analysis
        
-- Find total customers by coutries

SELECT 
    country, COUNT(DISTINCT customer_key) AS total_customers
FROM
    customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find total customers by gender

SELECT 
    gender, COUNT(DISTINCT customer_key) AS total_customers
FROM
    customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find total products by category

SELECT 
    category, COUNT(DISTINCT product_key) AS total_products
FROM
    products
GROUP BY category
ORDER BY total_products DESC;

-- Find the average cost of each category

SELECT 
    category, AVG(cost) AS avg_cost
FROM
    products
GROUP BY category
ORDER BY avg_cost DESC;

-- Find the total revenue generated by each category

SELECT 
    p.category, SUM(s.sales_amount) AS total_revenue
FROM
    products p
	 JOIN
    sales s ON p.product_key = s.product_key
GROUP BY category
ORDER BY total_revenue DESC;

-- What is the total revenue generated from each customer?

SELECT 
	c.customer_key,
    c.first_name,
    c.last_name,
    SUM(s.sales_amount) AS total_revenue
FROM
    customers c
       JOIN
    sales s ON s.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name , c.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of quantity sold by countries?

SELECT 
    c.country, SUM(s.quantity) AS quantity_sold
FROM
    customers c
        JOIN
    sales s ON c.customer_key = s.customer_key
GROUP BY c.country
ORDER BY quantity_sold DESC;



		-- 6. Ranking Analysis

-- Which 5 products generate the highest revenue?

SELECT
    p.product_name, SUM(s.sales_amount) AS total_revenue
FROM
    products p
        JOIN
    sales s ON p.product_key = s.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC
LIMIT 5;

-- What are the 5 worst performing products in terms of sales

SELECT
    p.product_name, SUM(s.sales_amount) AS total_revenue
FROM
    products p
        JOIN
    sales s ON p.product_key = s.product_key
GROUP BY p.product_name
ORDER BY total_revenue
LIMIT 5;

-- Using Window function

SELECT * FROM
(SELECT
    RANK() OVER (ORDER BY SUM(s.sales_amount)) AS ranking,
    p.product_name,
    SUM(s.sales_amount) AS total_revenue
FROM
    products p
        JOIN
    sales s ON p.product_key = s.product_key
GROUP BY p.product_name) a
WHERE ranking <= 5;

-- Find the top 10 customers who have generated the highest revenue

SELECT * FROM
(SELECT
RANK() OVER (ORDER BY SUM(s.sales_amount) DESC) AS ranking,
c.customer_key, c.first_name, c.last_name,
SUM(s.sales_amount) AS total_revenue
FROM customers c
JOIN sales s on c.customer_key = s.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name) a
WHERE ranking <= 10;

-- Find the top 3 customers with fewest orders placed

SELECT * FROM
(SELECT
RANK() OVER (ORDER BY COUNT(s.order_number)) AS ranking,
c.customer_key, c.first_name, c.last_name,
COUNT(DISTINCT s.order_number) AS total_orders
FROM customers c
JOIN sales s on c.customer_key = s.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name) a
WHERE ranking <= 3;